// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trigger.Persistence.Contexts;

#nullable disable

namespace Trigger.Persistence.Migrations
{
    [DbContext(typeof(TriggerDbContext))]
    [Migration("20220411125425_mg_1")]
    partial class mg_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("Trigger.Domain.Entities.Format", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Voice1Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Voice2Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Voice3Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Voice4Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Voice5Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Voice6Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Formats");
                });
#pragma warning restore 612, 618
        }
    }
}
